### ISSUE TITLE
Erro de Caracter Inválido na definição de uma Classe

### ISSUE THREAD

**Issue by mbcosta** [aricaldeira/PySPED#57]
Ola @aricaldeira parece que houve um erro de digitação em https://github.com/aricaldeira/PySPED/blob/master/pysped/nfe/leiaute/nfe_400.py#L67

**Comment by aricaldeira** [comment]
Opa, Magno, obrigado! Corrigido já. https://github.com/aricaldeira/PySPED/commit/2222f3a9fdfa39bfd9d6751a9eeb4f0b6c4537fb
